version: "3"
services:
  app:
    container_name: hme-server # How the container will appear when listing containers from the CLI
    ports:
    - "4000:4000" # <host-port>:<container-port> to listen to, so anything running on port 3000 of the container will map to port 3000 on our localhost
