FROM node:11

RUN apt-get update && apt-get -y upgrade

RUN apt-get install apt-transport-https

WORKDIR /usr/server/app

COPY package*.json ./

RUN npm install -g core-js
RUN npm install --production

COPY . .

EXPOSE 5000

RUN node -v
RUN npm -v

CMD ["node", "./index.cluster.js"]
