const globalActions = {
  FETCH_USER_PROFILE: 'GLOBAL/FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_LOADING: 'GLOBAL/FETCH_USER_PROFILE_LOADING',
  FETCH_USER_PROFILE_SUCCESS: 'GLOBAL/FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILURE: 'GLOBAL/FETCH_USER_PROFILE_FAILURE',
  FETCH_USER_EXTRA_PROFILE: 'GLOBAL/FETCH_USER_EXTRA_PROFILE',
  FETCH_USER_EXTRA_PROFILE_LOADING: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_LOADING',
  FETCH_USER_EXTRA_PROFILE_SUCCESS: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_SUCCESS',
  FETCH_USER_EXTRA_PROFILE_FAILURE: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_FAILURE',
};

export const FACEBOOK_LOGIN = 'APP/FACEBOOK_LOGIN';
export const FACEBOOK_LOGIN_LOADING = 'APP/FACEBOOK_LOGIN_LOADING';
export const FACEBOOK_LOGIN_SUCCESS = 'APP/FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAILURE = 'APP/FACEBOOK_LOGIN_FAILURE';

export const FACEBOOK_GET_LOCAL_DATA = 'APP/FACEBOOK_GET_LOCAL_DATA';

export default globalActions;
